import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/nav/Navbar'
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} dark text-foreground bg-background`}>
        <Providers>
        <div className="flex flex-col min-h-screen">
            <Navbar />
              <main className='flex-grow'>{children}</main>
            </div> 
        </Providers>
      </body>
    </html>
  );
}
